import "./globals.css";
import type { Metadata } from "next";
import { poppins } from "./font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={poppins.variable}>
      <head>
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css" />
      </head>
      <body className="font-poppins text-body-1 text-dark-3 bg-light-1">{children}</body>
    </html>
  );
}
